FIND_PATH(SLAM3D_INCLUDE_DIR slam3d/GraphMapper.hpp)
FIND_LIBRARY(SLAM3D_LIBRARY slam3d)

SET(SLAM3D_FOUND "NO")
IF(SLAM3D_INCLUDE_DIR AND SLAM3D_LIBRARY)
  SET(SLAM3D_FOUND "YES")
ENDIF(SLAM3D_INCLUDE_DIR AND SLAM3D_LIBRARY)

