# Find the header files
FIND_PATH(G2O_INCLUDE_DIR g2o/core/base_vertex.h)

# Macro to find the libraries
MACRO(FIND_G2O_LIBRARY TARGET_NAME LIBRARY_NAME)

  FIND_LIBRARY(${TARGET_NAME} "g2o_${LIBRARY_NAME}")
  
  IF(NOT TARGET g2o::${LIBRARY_NAME})
    ADD_LIBRARY(g2o::${LIBRARY_NAME} UNKNOWN IMPORTED)
    SET_TARGET_PROPERTIES(g2o::${LIBRARY_NAME} PROPERTIES
      IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
      IMPORTED_LOCATION "${LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${G2O_INCLUDE_DIR}")
  ENDIF()

ENDMACRO(FIND_G2O_LIBRARY TARGET_NAME LIBRARY_NAME)

# Find what is needed for slam3d (not everything from g2o)
FIND_G2O_LIBRARY(G2O_STUFF_LIBRARY stuff)
FIND_G2O_LIBRARY(G2O_CORE_LIBRARY core)
FIND_G2O_LIBRARY(G2O_SOLVER_CHOLMOD solver_cholmod)
FIND_G2O_LIBRARY(G2O_TYPES_SLAM3D types_slam3d)

# Handle behavior for find_package()
INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(G2O REQUIRED_VARS
  G2O_STUFF_LIBRARY
  G2O_CORE_LIBRARY
  G2O_TYPES_SLAM3D
  G2O_SOLVER_CHOLMOD
  G2O_INCLUDE_DIR
)

